version: '3'
services:
  front:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    container_name: vue-ui
    volumes:
       - ./:/usr/src/app/my-app
       - /usr/src/app/my-app/node_modules