version: '3'
services:
  front:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    container_name: challenge
    volumes:
       - ./:/usr/src/app/challenge
       - /usr/src/app/challenge/node_modules